### ISSUE TITLE
Energy definitely communicate on it's own frequency

### ISSUE THREAD

**Issue by idangoldman** [familyfriendlymikey/dot#1]
Yesterday, after deciding to actually try yabai and skhd, saw your video about them on youtube, OCRed your configs with cleanshot x and tried to run them... But the OCR conversion wasn't that good and I have ended up with search and replace needles of hit-missed.

@familyfriendlymikey, thanks for sharing your dots.

P.S. the chrome extension is also seems to be an interesting idea. 🧐

**Comment by familyfriendlymikey** [comment]
Haha sorry, I should have posted them in the first place :P To be honest I didn't think anybody would be that interested. But you're welcome!

The chrome extension is a huge boost for me. Hard to sell people on why though, kinda just gotta use it for real to understand :)

**Comment by idangoldman** [comment]
Well the chrome extension is more of a tool for people of specific type of workflow thinking or _sickos_ as you call them, and _psycho_ as called myself in the `ICQ` days.

Would be interesting to follow the evolvement of it.

**Comment by logiota** [comment]
Hi I liked your videos, do you think SKHD is hopeless for a remote that has many keys that MacOS seems to not recognize at all and not skid -o either ?
